### ISSUE TITLE
`coverify` doesn't work with `babelify@^6.0.0` or `babelify@^7.0.0`

### ISSUE THREAD

**Issue by f5io** [substack/coverify#22]
The following works with `babelify: "^5.0.0"`:

```
node_modules/.bin/browserify -t babelify -t coverify --bare --node  ./test/*.spec.js | node | node_modules/.bin/coverify
```

However, when using `babelify: "^6.0.0"`, I get the following error with the same command:

```
ypeError: __coverageWrap(...)(...) is not a function
    at [stdin]:1847:108
    at Object.31../module.js ([stdin]:1865:3)
    at s ([stdin]:1:254)
    at e ([stdin]:1:425)
    at [stdin]:1:443
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:434:26)
    at node.js:567:27
    at doNTCallback0 (node.js:408:9)
```

And using `babelify: "^7.0.0"`, I get a different error:

```
node_modules/coverify/node_modules/source-map/lib/source-map/source-map-consumer.js:697
        throw new Error('"' + aSource + '" is not in the SourceMap.');
```

I know these errors are more likely to do with `babel` and `babelify`, but is there a way I can at least get `coverify` running on `babelify@^6.0.0`?

Any help would be appreciated.

**Comment by lusentis** [comment]
Same
            throw new Error('"' + aSource + '" is not in the SourceMap.');
here :(

```
$ babel --version
6.4.0 (babel-core 6.4.0)
$ node --version
v5.1.0
$ browserify --version
12.0.1
```

**Comment by kuraga** [comment]
From https://github.com/substack/node-browserify/issues/1462:

```js
var testFiles = globSync(path.join('test', '**', '*Test.js'));
browserify(testFiles, {debug: true})
  .transform('babelify')
  .transform('coverify')
  .bundle()
  .pipe(process.stdout);
```
seems like [`coverify` plugin](https://github.com/substack/coverify) gets (first) source map with `appTest.js` only (without path).

**Comment by kuraga** [comment]
@lusentis no, it's another issue: #23

**Comment by kuraga** [comment]
@substack but this is still actually... Could you help, please?

Seems like this is connected with `insertGlobalVars`. Seems like Browserify inserts/replaces/etc. _after_ Coverify wraps functions.

Or wrapping doesn't work properly with [these](https://github.com/Raynos/global/blob/904a038384ee6c3889d550c9721a09260dda4f6b/package.json#L20) in my case.

Because I get:
```
  { __coverageWrap(103);(__coverageWrap(102)(((__coverageWrap(37)(0, (__coverageWrap(36)(_createClass3.default)))))(Cursor_FreezerJs, (__coverageWrap(101)([(__coverageWrap(43)({
                                                                                                                   ^

TypeError: __coverageWrap(...)(...) is not a function
```
...and about `103` module see [here](https://github.com/substack/node-browserify/issues/1549).

Thanks!

**Comment by kuraga** [comment]
@substack ping

**Comment by brokenalarms** [comment]
This is still not working for me either. Adding `--sourceMapsAbsolute` to babelify solves the 'not in the sourceMap error', but leads to the same one that @kuraga has pointed out.

- `browserify -t [ babelify --presets [ es2015 ] --sourceMapsAbsolute ] -t coverify --bare test/index.js | node | coverify` as as `npm run` command gives the `coverageWrap` error above.
- running directly from console as `browserify -t [ babelify --presets [ es2015 ] --sourceMapsAbsolute ] -t coverify --bare --node  ./test/index.js | node | node_modules/.bin/coverify` gives:

```javascript
[stdin]:13154
    oldHandlers[ext] = require.extensions[ext];
                                         ^

TypeError: Cannot read property '.js' of undefined
    at [stdin]:13154:42
    at arrayEach ([stdin]:34835:9)
    at forEach ([stdin]:39457:10)
    at hookExtensions ([stdin]:13153:22)
    at Object.158../cache ([stdin]:13159:1)
    at s ([stdin]:1:254)
    at [stdin]:1:305
    at Object.135.babel-register ([stdin]:9365:18)
    at s ([stdin]:1:254)
    at [stdin]:1:305
# coverage: 0/0 (0.00 %)
```
Hope that helps!
